// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF3W6Cieu5dSTl_rBzrdAG-JKPvz0bPOo',
    appId: '1:228768267803:web:078ce18f77da1a367102be',
    messagingSenderId: '228768267803',
    projectId: 'bartlo-15811',
    authDomain: 'bartlo-15811.firebaseapp.com',
    databaseURL: 'https://bartlo-15811-default-rtdb.firebaseio.com',
    storageBucket: 'bartlo-15811.appspot.com',
    measurementId: 'G-WNGE5LF4NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbiOxCCrQ1BJsbwcXr-s56n_8TwF77Umg',
    appId: '1:228768267803:android:db7f1fa5887226d97102be',
    messagingSenderId: '228768267803',
    projectId: 'bartlo-15811',
    databaseURL: 'https://bartlo-15811-default-rtdb.firebaseio.com',
    storageBucket: 'bartlo-15811.appspot.com',
  );
}
